#!/bin/bash
bear --output "../misc/compile_commands.json" -- make -B -k SILENT_OUTPUT=@ DEBUG=1 PROFILER_ENABLED=1 ASSERT_ENABLED=1 INTERNAL_BUILD=1 DLL_RELOADING=0 RENDERER_BACKEND=OPENGL MEMORY_DEBUGGING=0
